package lushnalv.fel.cvut.cz.constants

enum class ResponseConstants(val value: String) {
    SUCCESS("success"),
    ERROR("error"),
    UNKNOWN("UNKNOWN"),

    INVALID_TRIP_TITLE("TRIP_001"),
    INVALID_TRIP_ID("TRIP_002"),
    INVALID_TRIP_OWNER("TRIP_003"),

    INVALID_DAY_ID("DAY_001"),
    POINTS_ARE_IN_DIFFERENT_DAYS("DAY_002"),
    DAY_POINT_IS_NOT_START_POINT("DAY_003"),


    INVALID_DAY_POINT_ID("DAY_POINT_001"),



    INVALID_CREDENTIAL("USR001"),
    INVALID_EMAIL("USR002"),
    EMAIL_ALREADY_EXIST("USR003"),
    USER_DOES_NOT_EXIST("USR004"),
    INVALID_USER_DATA("USR005"),
    INVALID_GOOGLE_TOKEN("USR006"),
    INCORRECT_RESET_CODE("USR007"),

    AMOUNT_IS_EMPTY_OR_NEGATIVE("DUTY001"),
    USER_IS_NOT_IN_TRIP("DUTY002"),

    INVALID_COMMENT("COMM_001"),

    USER_CANT_PERFORM_THIS_ACTION("USR008")
}